version: '2'
services:
  nginx:
    build: ./nginx/
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_dehydrated:/etc/dehydrated/
    depends_on:
      - searx
    links:
      - searx

searx:
  image: wonderfall/searx:latest
  restart: always

volumes:
  nginx_dehydrated:
